### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by saikiran6-1-6** [Bx16/hackintosh-Huawei-D14-2019-AMD#1]
I have the same hardware as you,  if you can share your EFI ill be able to test out what's working and what's not.

**Comment by Bx16** [comment]
Installer is not booting right now, so there is not much to test :(

**Comment by saikiran6-1-6** [comment]
Ok,Thanks.

**Comment by Bx16** [comment]
hi @Destroyer616 you can test now with ventura

**Comment by saikiran6-1-6** [comment]
Hi, I tried the new EFI and I'm able to boot into the installer. But my internal sandisk SSD isn't working, is there anything that i could try.

**Comment by Bx16** [comment]
I replaced my msata disk with lexar nvme because I cant find working sata kext for stock disk, you can try with sata kexts (google) but not worked for me

**Comment by saikiran6-1-6** [comment]
Will try to replace msata with nvme and give it a try. also i got the touchpad working by replacing the Voodo kexts with the kexts present in this repo https://github.com/adhocfra/HuaweiMatebookD14RyzenHackintosh, try and see if it works for. u.
